# Generated by Django 3.1 on 2020-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='URL',
            new_name='url',
        ),
        migrations.AddField(
            model_name='record',
            name='path_name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
